<a href="https://colab.research.google.com/github/Deekshitha-max/Java-calculator/blob/calculate/multimodel_AI_on_HD_Deekshitha.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Design and Implementation of a Mutimodel AI Agent for Automated Health Diagnosis

My view on this Project~
In this Project my goal is to build a small data Processing Pipeline that can identify,extract,validate and Standardize medical parameters from raw  data sets.
Real world medical data is often incomplete and inconsistently formatted,so we have to clean the data set and keep in structured form that is used for future analysis

working on Data gathering: I collected dataset(kidney Disease dataset) from kaggle.This dataset contain multiple clinical Parameters such as  hemoglobin,redblood cells and other measurements related to kidney health

Step 1: Load the Dataset

In [5]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/kidney_disease.csv")
display(df.head())

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

cleaning Data

Parameter Identification and Extraction:
Many of the Parameters in the raw data set were inconsistent.so I normalized the column names and Extract the key parameters that would be used for diagnostics.I also identified whether each parameter was numerical or categorical

In [6]:
df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")
df.head()

,id,age,bp,sg,al,su,rbc,pc,pcc,ba,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,0,48.0,80.0,1.020,1.0,0.0,NaN,normal,notpresent,notpresent,...,44,7800,5.2,yes,yes,no,good,no,no,ckd
1,1,7.0,50.0,1.020,4.0,0.0,NaN,normal,notpresent,notpresent,...,38,6000,NaN,no,no,no,good,no,no,ckd
2,2,62.0,80.0,1.010,2.0,3.0,normal,normal,notpresent,notpresent,...,31,7500,NaN,no,yes,no,poor,no,yes,ckd
3,3,48.0,70.0,1.005,4.0,0.0,normal,abnormal,present,notpresent,...,32,6700,3.9,yes,no,no,poor,yes,yes,ckd
4,4,51.0,80.0,1.010,2.0,0.0,normal,normal,notpresent,notpresent,...,35,7300,4.6,no,no,no,good,no,no,ckd

Identify key medical parameters
 Extract into a separate DataFrame

In [7]:
# list of important medical parameters present in the kidney dataset
important_cols = [
    "age","bp","bgr","bu","sc","sod","pot","hemo","pcv",
    "wc","rc","htn","dm","cad","appet","pe","ane"
]

extracted = df[important_cols]
extracted.head()

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,121.0,36.0,1.2,NaN,NaN,15.4,44,7800,5.2,yes,yes,no,good,no,no
1,7.0,50.0,NaN,18.0,0.8,NaN,NaN,11.3,38,6000,NaN,no,no,no,good,no,no
2,62.0,80.0,423.0,53.0,1.8,NaN,NaN,9.6,31,7500,NaN,no,yes,no,poor,no,yes
3,48.0,70.0,117.0,56.0,3.8,111.0,2.5,11.2,32,6700,3.9,yes,no,no,poor,yes,yes
4,51.0,80.0,106.0,26.0,1.4,NaN,NaN,11.6,35,7300,4.6,no,no,no,good,no,no

3.Data Validation and Standardization:The raw dataset contained missing values, outliers, inconsistent spellings, and mixed data types. To make the datausable, I validated:
Data type correctness
Missing or blank values
Invalid symbols
Value ranges for numerical features
Unexpected categories in categorical features

In [8]:
print("Missing values in each column:\n")
print(extracted.isnull().sum())

Missing values in each column:

age        9
bp        12
bgr       44
bu        19
sc        17
sod       87
pot       88
hemo      52
pcv       70
wc       105
rc       130
htn        2
dm         2
cad        2
appet      1
pe         1
ane        1
dtype: int64

converting into Numeric Data

In [9]:
num_cols = ["age","bp","bgr","bu","sc","sod","pot","hemo","pcv","wc","rc"]

# convert non-numerical values to NaN
for col in num_cols:
    extracted[col] = pd.to_numeric(extracted[col], errors="coerce")

/tmp/ipython-input-396435442.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = pd.to_numeric(extracted[col], errors="coerce")

Fill missing numeric values

In [10]:
for col in num_cols:
    extracted[col] = extracted[col].fillna(extracted[col].median())

/tmp/ipython-input-1581286923.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].fillna(extracted[col].median())

Handle categorical columns

In [11]:
cat_cols = ["htn","dm","cad","appet","pe","ane"]

for col in cat_cols:
    extracted[col] = extracted[col].fillna(extracted[col].mode()[0])

/tmp/ipython-input-3221403211.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].fillna(extracted[col].mode()[0])

Data Standardization and cleaning: To prepare clean Data set ready for analysis-Replaced missing numeric values with median values-Replaced missing categorical values with mode-converting numerical values from integer to float-Standardize column names by using lower case letters,unserscores,and removing extraspaces

Standardize categorical values

In [12]:
for col in cat_cols:
    extracted[col] = extracted[col].astype(str).str.lower()
    extracted[col] = extracted[col].replace({
        "yes":1, "y":1, "present":1,
        "no":0, "n":0, "absent":0
    })

/tmp/ipython-input-958618850.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].astype(str).str.lower()
/tmp/ipython-input-958618850.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  extracted[col] = extracted[col].replace({
/tmp/ipython-input-958618850.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].replace({
/tmp/ipython-input-958618850.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].astype(str).str.lower()
/tmp/ipython-input-958618850.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].replace({
/tmp/ipython-input-958618850.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].astype(str).str.lower()
/tmp/ipython-input-958618850.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].replace({
/tmp/ipython-input-958618850.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].astype(str).str.lower()
/tmp/ipython-input-958618850.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].replace({
/tmp/ipython-input-958618850.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].astype(str).str.lower()
/tmp/ipython-input-958618850.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  extracted[col] = extracted[col].replace({
/tmp/ipython-input-958618850.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].replace({
/tmp/ipython-input-958618850.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].astype(str).str.lower()
/tmp/ipython-input-958618850.py:3: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  extracted[col] = extracted[col].replace({
/tmp/ipython-input-958618850.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  extracted[col] = extracted[col].replace({

Standardized Dataset

In [13]:
print("Final cleaned dataset:")
extracted.head()

Final cleaned dataset:

,age,bp,bgr,bu,sc,sod,pot,hemo,pcv,wc,rc,htn,dm,cad,appet,pe,ane
0,48.0,80.0,121.0,36.0,1.2,138.0,4.4,15.4,44.0,7800.0,5.2,1,1,0,good,0,0
1,7.0,50.0,121.0,18.0,0.8,138.0,4.4,11.3,38.0,6000.0,4.8,0,0,0,good,0,0
2,62.0,80.0,423.0,53.0,1.8,138.0,4.4,9.6,31.0,7500.0,4.8,0,1,0,poor,0,1
3,48.0,70.0,117.0,56.0,3.8,111.0,2.5,11.2,32.0,6700.0,3.9,1,0,0,poor,1,1
4,51.0,80.0,106.0,26.0,1.4,138.0,4.4,11.6,35.0,7300.0,4.6,0,0,0,good,0,0